### ISSUE TITLE
Hardcoded Baud on Serial

### ISSUE THREAD

**Issue by Westiewombat** [createcandle/Webthings-mysensors-adapter#17]
More of a request than an issue.
Unable to modify the baud rate which is hardcoded into mysensors_adapter.
This is causing issues with serial connectivity to MCU and TTL UART - FTDI or CH340 and Linux O/S and Webthings container

Would appreciate a parameter (pull down) to specify the speed supported by pyserial

**Comment by createcandle** [comment]
What options would you need?

**Comment by Westiewombat** [comment]
Hi

Baud Options supported by gateway serial uarts 19200, 38400, 57600, 115200.

Much appreciated

**Comment by createcandle** [comment]
The next version will have this feature.
