### ISSUE TITLE
RGB Lights have no colour property setting

### ISSUE THREAD

**Issue by renatose** [createcandle/Webthings-mysensors-adapter#19]
I made my own code for an Arduino as a RGB led strip controller based widely available examples.
Turning on/off and setting the dim level works okay, but the colour setting is unavailable.

I noticed that it seems to be an undocumented missing feature:
https://github.com/createcandle/Webthings-mysensors-adapter/blob/master/pkg/mysensors_device.py#L884

Subtype V_RGB is avaliable for Color sensor but not for RGB or RGBW lights.
If it is a known missing feature it should be documented as so, so that it does not get forgotten.

In any case I would like to understand and help, is there any limitation on Webthings to have this feature? How can I help?

**Comment by createcandle** [comment]
It should be added now (RGB only, not RGBW). Thanks for pointing it out.

**Comment by renatose** [comment]
Great, I'm trying to put it to good use, but...
It seems that there is an extra hashtag char being sent.

`ERROR  : mysensors-adapter: Invalid <Message data="2;1;1;0;40;#fcfcfc">: #fcfcfc is not six characters long for object value @ data['payload']. Got '#fcfcfc'`

**Comment by renatose** [comment]
And S_RGB_LIGHT (26) should support not only V_RGB (40), but also V_STATUS (2) and V_PERCENTAGE (3) as it did before the change.
