### ISSUE TITLE
MainType 13 Power MEasuring Device needs EnergyMonitor Type

### ISSUE THREAD

**Issue by Westiewombat** [createcandle/Webthings-mysensors-adapter#21]
Hi again

Can you please add self._type.append('EnergyMonitor') to V_WATT and V_KWH under Power. Testing this provides a better looking icon on the Things page. I can upload an image (png) ... 

Thanks

            elif new_main_type == 13:                      # Power measuring device, like power meters
                if new_sub_type == 17: # V_WATT
                    self._type.append('EnergyMonitor')
                    self.properties[targetPropertyID] = MySensorsProperty(
                        self,
                        targetPropertyID,
                        {
                            '@type': 'InstantaneousPowerProperty',
                            'label': new_description,
                            'type': 'number',
                            'unit': 'watt',
                            'readOnly': True,
                            'multipleOf':0.01,
                        },
                        values, new_value, new_node_id, new_child_id, new_main_type, new_sub_type)
                if new_sub_type == 18: # V_KWH
                    self._type.append('EnergyMonitor')
                    self.properties[targetPropertyID] = MySensorsProperty(
                        self,
                        targetPropertyID,
                        {
                            'label': new_description,
                            'type': 'number',
                            'unit': 'kwh',
                            'readOnly': True,
                            'multipleOf':0.001,
                        },
                        values, new_value, new_node_id, new_child_id, new_main_type, new_sub_type)

**Comment by createcandle** [comment]
Yes. Next version will have the changes.

**Comment by Westiewombat** [comment]
Hi - I see the update on git (1.2.6), but no update being downloaded 1.2.4?

**Comment by createcandle** [comment]
Your wish is my command
