### ISSUE TITLE
 Permission denied on file mysensors-adapter-persistence.json 

### ISSUE THREAD

**Issue by extrablind** [createcandle/Webthings-mysensors-adapter#8]
Hello, 

soon after starting the gateway I've got this in logs : 
`2020-03-06 01:36:18.435 ERROR  : mysensors-adapter: Permission denied when writing to /root/.mozilla-iot/data/mysensors-adapter/mysensors-adapter-persistence.json`

Steps to reproduce :
- Lauching "sudo webthings-gateway" (so as root)
- Adding MySensor add-on and configure it properly
- Connect USB gateway which is r/w capable
- Start scanning

Same thing when manually creating the file as root or chmod it badly in 777 for testing purpose.

Thanks for your work. 
Regards ,

**Comment by createcandle** [comment]
Does this only happen if you are root?

**Comment by createcandle** [comment]
My recommendation would be to not run the gateway as root.
