### ISSUE TITLE
Cross-compile rather than bootstrap

### ISSUE THREAD

**Issue by mrstegeman** [createcandle/Webthings-mysensors-adapter#9]
The [addon-builder](https://github.com/mozilla-iot/addon-builder) now has support for cross-compiling Python add-ons for various architectures and Python versions. It would be helpful to use it rather than bootstrapping on target in the background for a (long) time before being able to actually start up. I've done this for the Eufy add-on, as an example.

* `package.sh` change: https://github.com/mozilla-iot/eufy-adapter/commit/5cd3c3c394802b23e4ee402d3ea4befbb901d434
* addon-builder change: https://github.com/mozilla-iot/addon-builder/pull/49
* addon-list change: https://github.com/mozilla-iot/addon-list/pull/817

**Comment by createcandle** [comment]
done
